# Generated by Django 3.0.1 on 2020-01-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='images')),
                ('urlfield', models.URLField()),
                ('summary', models.CharField(max_length=200)),
                ('github', models.URLField(max_length=255)),
            ],
        ),
    ]
